---
components:
  - name: tca95x5
    description: |
      Driver for TCA9535/TCA9555 remote 16-bit I/O expanders for I2C-bus
    group: gpio
    groups: []
    code_owners: UncleRus
    depends:
      - i2cdev
      - log
      - esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: UncleRus
        year: 2019
