---
components:
  - name: max31725
    description: Driver for MAX31725/MAX31726 temperature sensors
    group: temperature
    groups: []
    code_owners: UncleRus
    depends:
      - i2cdev
      - log
      - esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: UncleRus
        year: 2020
