---
components:
  - name: aht
    description: |
      Driver for AHT10/AHT15/AHT20 temperature and humidity sensor
    group: temperature
    groups:
      - humidity
    code_owners:
      - name: UncleRus
    depends:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - name: UncleRus
        year: 2021
