---
components:
  - name: hmc5883l
    description: |
      Driver for 3-axis digital compass HMC5883L
    group: magnetic
    groups: []
    code_owners:
      - name: UncleRus
    depends:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - name: UncleRus
        year: 2016
