---
components:
  - name: ccs811
    description: |
      Driver for AMS CCS811 digital gas sensor
    group: air-quality
    groups:
      - name: gas
    code_owners:
      - name: UncleRus
    depends:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - name: UncleRus
        year: 2021
      - name: gschorcht
        year: 2017
