---
components:
  - name: mcp4725
    description: Driver for 12-bit DAC MCP4725
    group: adc-dac
    groups: []
    code_owners: UncleRus
    depends:
      - i2cdev
      - log
      - esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: UncleRus
        year: 2016
