---
components:
  - name: pcf8591
    description: Driver for 8-bit ADC and an 8-bit DAC PCF8591
    group: adc-dac
    groups: []
    code_owners: UncleRus
    depends:
      - i2cdev
      - log
      - esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: UncleRus
        year: 2017
      - author:
          name: PhamNgocT
        year: 2017
