---
components:
  - name: bmp180
    description: |
      Driver for BMP180 digital pressure sensor
    group:
      name: pressure
    groups:
      - name: temperature
    code_owners:
      - name: UncleRus
    depends:
      - name: i2cdev
      - name: log
      - name: esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: MIT
    copyrights:
      - name: UncleRus
        year: 2018
      - name: FrankB
        year: 2015
