---
components:
  - name: tsl2561
    description: Driver for light-to-digital converter TSL2561
    group: light
    groups: []
    code_owners: UncleRus
    depends:
      - i2cdev
      - log
      - esp_idf_lib_helpers
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: UncleRus
        year: 2018
      - author:
          name: bschwind
        year: 2016
