---
components:
  - name: ds1302
    description: |
      Driver for DS1302 RTC module
    group: rtc
    groups: []
    code_owners:
      - name: UncleRus
    depends:
      - name: log
      - name: esp_idf_lib_helpers
      - name: freertos
      - name: driver
    thread_safe: no
    targets:
      - name: esp32
      - name: esp8266
    licenses:
      - name: BSD-3
    copyrights:
      - name: UncleRus
        year: 2021
      - name: PavelM
        year: 2016
